name: Send Email

on:
  push:
    branches:
      - main 

jobs:
  sendEmail:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Use the appropriate Node.js version

      - name: Install dependencies
        run: |
          npm install nodemailer

      - name: Send Email
        run: node sendEmail.js
